package lab5_carlosfortin_11911015;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Carlos Fortin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.pack();
        usuarios.add(new Usuario("Carlos", "Fortin", "SkyCafl", "1234", new Date(), Color.blue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_agrnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_agrapellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_agrusuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pf_agrpassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        dc_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jb_color = new javax.swing.JButton();
        jb_agrregistro = new javax.swing.JButton();
        jd_menu = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mazos = new javax.swing.JTree();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_miembros = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jd_agregarcartas = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb_mazo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cb_tipocarta = new javax.swing.JComboBox<>();
        tf_nombrecarta = new javax.swing.JTextField();
        tf_ptsvida = new javax.swing.JTextField();
        tf_ptsdaño = new javax.swing.JTextField();
        jb_agrmazo = new javax.swing.JButton();
        jd_crearclan = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreclan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cb_rango = new javax.swing.JComboBox<>();
        jb_crear = new javax.swing.JButton();
        jd_unirclan = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_clanes = new javax.swing.JList<>();
        jb_unirse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jb_ingresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jb_registro = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText("Registro");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Nombre de usuario");

        jLabel10.setText("Password");

        jLabel11.setText("Fecha de nacimiento");

        jLabel12.setText("Color favorito");

        jb_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorMouseClicked(evt);
            }
        });

        jb_agrregistro.setText("Registrarse");
        jb_agrregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agrregistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_agrregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_registroLayout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(jLabel6))
                        .addGroup(jd_registroLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_registroLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(dc_nacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jd_registroLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pf_agrpassword))
                                    .addComponent(jLabel9)
                                    .addGroup(jd_registroLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_agrnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_registroLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_agrapellido))
                                    .addComponent(tf_agrusuario))))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_agrnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_agrapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_agrusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pf_agrpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dc_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jb_agrregistro)
                .addGap(89, 89, 89))
        );

        jLabel13.setText("Tus mazos");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 3");
        treeNode1.add(treeNode2);
        jt_mazos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_mazos);

        jLabel14.setText("Tu clan");

        jScrollPane2.setViewportView(jl_miembros);

        jMenu1.setText("Mazos");

        jMenuItem1.setText("Agregar cartas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clan");

        jMenuItem3.setText("Crear clan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Unirse a un clan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setText("Salir del clan actual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jd_menu.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_menuLayout = new javax.swing.GroupLayout(jd_menu.getContentPane());
        jd_menu.getContentPane().setLayout(jd_menuLayout);
        jd_menuLayout.setHorizontalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jd_menuLayout.setVerticalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("Agregar Cartas");

        jLabel16.setText("Seleccione un mazo");

        cb_mazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mazo 1", "Mazo 2", "Mazo 3" }));

        jLabel17.setText("Nombre");

        jLabel18.setText("Puntos de vida");

        jLabel19.setText("Puntos de daño");

        jLabel20.setText("Tipo de Carta");

        cb_tipocarta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Leñador", "Golem", "Gigante", "Duendes", "Dragon Infernal", "Dragon" }));

        jb_agrmazo.setText("Agregar");
        jb_agrmazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agrmazoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarcartasLayout = new javax.swing.GroupLayout(jd_agregarcartas.getContentPane());
        jd_agregarcartas.getContentPane().setLayout(jd_agregarcartasLayout);
        jd_agregarcartasLayout.setHorizontalGroup(
            jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombrecarta))
                            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cb_mazo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ptsvida))
                            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_ptsdaño))
                            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tipocarta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_agrmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jd_agregarcartasLayout.setVerticalGroup(
            jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(40, 40, 40)
                .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(cb_mazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nombrecarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(tf_ptsvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_ptsdaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agregarcartasLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jb_agrmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(cb_tipocarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setText("Crear Clan");

        jLabel22.setText("Nombre");

        jLabel23.setText("Rango");

        cb_rango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro", "Legendario" }));

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearclanLayout = new javax.swing.GroupLayout(jd_crearclan.getContentPane());
        jd_crearclan.getContentPane().setLayout(jd_crearclanLayout);
        jd_crearclanLayout.setHorizontalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel21))
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel22)
                        .addGap(26, 26, 26)
                        .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearclanLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(cb_rango, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_nombreclan, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jd_crearclanLayout.setVerticalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addGap(60, 60, 60)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_nombreclan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cb_rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setText("Unirse a un clan");

        jl_clanes.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_clanes);

        jb_unirse.setText("Unirse");
        jb_unirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_unirseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_unirclanLayout = new javax.swing.GroupLayout(jd_unirclan.getContentPane());
        jd_unirclan.getContentPane().setLayout(jd_unirclanLayout);
        jd_unirclanLayout.setHorizontalGroup(
            jd_unirclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_unirclanLayout.createSequentialGroup()
                .addGroup(jd_unirclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_unirclanLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel24))
                    .addGroup(jd_unirclanLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jb_unirse, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jd_unirclanLayout.setVerticalGroup(
            jd_unirclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_unirclanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel24)
                .addGroup(jd_unirclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_unirclanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_unirclanLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jb_unirse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Clash Royale");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setText("Usuario");

        jLabel4.setText("Password");

        jb_ingresar.setText("Ingresar");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });

        jLabel5.setText("No tienes cuenta?");

        jb_registro.setText("Registrate");
        jb_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_usuario)
                                .addComponent(pf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jb_ingresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_registro)
                            .addComponent(jLabel5))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_ingresar)
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_registro)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registroMouseClicked
        jd_registro.setVisible(true);
        jd_registro.pack();
        //jd_registro.setModal(true);
    }//GEN-LAST:event_jb_registroMouseClicked

    private void jb_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorMouseClicked
        jb_color.setBackground(JColorChooser.showDialog(jd_registro, "Seleccione un color", Color.blue));
    }//GEN-LAST:event_jb_colorMouseClicked

    private void jb_agrregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agrregistroMouseClicked
        usuarios.add(new Usuario(tf_agrnombre.getText(), tf_agrapellido.getText(), tf_agrusuario.getText(), pf_agrpassword.getText(), dc_nacimiento.getDate(), jb_color.getBackground()));
        tf_agrnombre.setText("");
        tf_agrapellido.setText("");
        tf_agrusuario.setText("");
        pf_agrpassword.setText("");
        dc_nacimiento.setDate(null);
        jb_color.setBackground(Color.blue);
        JOptionPane.showMessageDialog(jd_registro, "Usuario registrado correctamente");
        jd_registro.dispose();
        //this.setVisible(true);
        
    }//GEN-LAST:event_jb_agrregistroMouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        if(tf_usuario.getText()!=null && pf_password.getText()!=null){
            for (Usuario u : usuarios) {
                if(u.getNombre_usuario().equals(tf_usuario.getText())){
                    if(u.getNombre_usuario().equals(tf_usuario.getText()) && u.getPassword().equals(pf_password.getText())){
                        actual=u;
                        JOptionPane.showMessageDialog(this, "Se ha ingresado correctamente");
                        System.out.println(actual.getEdad());
                        jd_menu.setVisible(true);
                        jd_menu.pack();
                        break;
                    }
                }
            }
            tf_usuario.setText("");
            pf_password.setText("");
            if(actual==null)
                JOptionPane.showMessageDialog(this, "El usuario o la password es incorrecta");
        }
        else
            JOptionPane.showMessageDialog(this, "Debe ingresar sesion");
    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jb_agrmazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agrmazoMouseClicked
        
        DefaultTreeModel modelo=(DefaultTreeModel)jt_mazos.getModel();
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)modelo.getRoot();
        
        if(cb_mazo.getSelectedItem().toString().equals("Mazo 1")){
            if(actual.getMazo1().getCartas().size()<3){
                if(cb_tipocarta.getSelectedItem().toString().equals("Minipekka"))
                    actual.getMazo1().setCarta(new Minipekka());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Montapuerco"))
                    actual.getMazo1().setCarta(new Montapuerco());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Leñador"))
                    actual.getMazo1().setCarta(new Leñador());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Golem"))
                    actual.getMazo1().setCarta(new Golem());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Gigante"))
                    actual.getMazo1().setCarta(new Gigante());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Duendes"))
                    actual.getMazo1().setCarta(new Duendes());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon Infernal"))
                    actual.getMazo1().setCarta(new Dragon_Infernal());
                
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon"))
                    actual.getMazo1().setCarta(new Dragon());   
                
                    
                actual.getMazo1().getCartas().get(actual.getMazo1().getCartas().size()-1).setNombre(tf_nombrecarta.getText());
                actual.getMazo1().getCartas().get(actual.getMazo1().getCartas().size()-1).setPts_vida(Integer.parseInt(tf_ptsvida.getText()));
                actual.getMazo1().getCartas().get(actual.getMazo1().getCartas().size()-1).setDaño(Integer.parseInt(tf_ptsdaño.getText()));
                
                Carta c=actual.getMazo1().getCartas().get(actual.getMazo1().getCartas().size()-1);
                
                
                DefaultMutableTreeNode rango=new DefaultMutableTreeNode(c.getRango());
                DefaultMutableTreeNode carta=new DefaultMutableTreeNode(rango);
                ((DefaultMutableTreeNode)root.getChildAt(0)).add(rango);
                rango.add(carta);
                modelo.reload();
                
            }
            else
                JOptionPane.showMessageDialog(jd_agregarcartas, "El mazo no puede tener mas de 3 cartas");
        }
        if(cb_mazo.getSelectedItem().toString().equals("Mazo 2")){
            if(actual.getMazo2().getCartas().size()<3){
                if(cb_tipocarta.getSelectedItem().toString().equals("Minipekka"))
                    actual.getMazo2().setCarta(new Minipekka());
                if(cb_tipocarta.getSelectedItem().toString().equals("Montapuerco"))
                    actual.getMazo2().setCarta(new Montapuerco());
                if(cb_tipocarta.getSelectedItem().toString().equals("Leñador"))
                    actual.getMazo2().setCarta(new Leñador());
                if(cb_tipocarta.getSelectedItem().toString().equals("Golem"))
                    actual.getMazo2().setCarta(new Golem());
                if(cb_tipocarta.getSelectedItem().toString().equals("Gigante"))
                    actual.getMazo2().setCarta(new Gigante());
                if(cb_tipocarta.getSelectedItem().toString().equals("Duendes"))
                    actual.getMazo2().setCarta(new Duendes());
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon Infernal"))
                    actual.getMazo2().setCarta(new Dragon_Infernal());
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon"))
                    actual.getMazo2().setCarta(new Dragon());    
                    
                actual.getMazo2().getCartas().get(actual.getMazo2().getCartas().size()-1).setNombre(tf_nombrecarta.getText());
                actual.getMazo2().getCartas().get(actual.getMazo2().getCartas().size()-1).setPts_vida(Integer.parseInt(tf_ptsvida.getText()));
                actual.getMazo2().getCartas().get(actual.getMazo2().getCartas().size()-1).setDaño(Integer.parseInt(tf_ptsdaño.getText()));
                
                Carta c=actual.getMazo2().getCartas().get(actual.getMazo2().getCartas().size()-1);
                
                
                DefaultMutableTreeNode rango=new DefaultMutableTreeNode(c.getRango());
                DefaultMutableTreeNode carta=new DefaultMutableTreeNode(rango);
                ((DefaultMutableTreeNode)root.getChildAt(1)).add(rango);
                rango.add(carta);
                modelo.reload();
            }
            else
                JOptionPane.showMessageDialog(jd_agregarcartas, "El mazo no puede tener mas de 3 cartas");
        }
        if(cb_mazo.getSelectedItem().toString().equals("Mazo 3")){
            if(actual.getMazo3().getCartas().size()<3){
                if(cb_tipocarta.getSelectedItem().toString().equals("Minipekka"))
                    actual.getMazo3().setCarta(new Minipekka());
                if(cb_tipocarta.getSelectedItem().toString().equals("Montapuerco"))
                    actual.getMazo3().setCarta(new Montapuerco());
                if(cb_tipocarta.getSelectedItem().toString().equals("Leñador"))
                    actual.getMazo3().setCarta(new Leñador());
                if(cb_tipocarta.getSelectedItem().toString().equals("Golem"))
                    actual.getMazo3().setCarta(new Golem());
                if(cb_tipocarta.getSelectedItem().toString().equals("Gigante"))
                    actual.getMazo3().setCarta(new Gigante());
                if(cb_tipocarta.getSelectedItem().toString().equals("Duendes"))
                    actual.getMazo3().setCarta(new Duendes());
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon Infernal"))
                    actual.getMazo3().setCarta(new Dragon_Infernal());
                if(cb_tipocarta.getSelectedItem().toString().equals("Dragon"))
                    actual.getMazo3().setCarta(new Dragon());    
                    
                actual.getMazo3().getCartas().get(actual.getMazo3().getCartas().size()-1).setNombre(tf_nombrecarta.getText());
                actual.getMazo3().getCartas().get(actual.getMazo3().getCartas().size()-1).setPts_vida(Integer.parseInt(tf_ptsvida.getText()));
                actual.getMazo3().getCartas().get(actual.getMazo3().getCartas().size()-1).setDaño(Integer.parseInt(tf_ptsdaño.getText()));
                
                Carta c=actual.getMazo3().getCartas().get(actual.getMazo3().getCartas().size()-1);
                
                
                DefaultMutableTreeNode rango=new DefaultMutableTreeNode(c.getRango());
                DefaultMutableTreeNode carta=new DefaultMutableTreeNode(rango);
                ((DefaultMutableTreeNode)root.getChildAt(2)).add(rango);
                rango.add(carta);
                modelo.reload();
            }
            else
                JOptionPane.showMessageDialog(jd_agregarcartas, "El mazo no puede tener mas de 3 cartas");
        }
        System.out.println(actual.getMazo1().getCartas());
        
        tf_nombrecarta.setText("");
        tf_ptsvida.setText("");
        tf_ptsdaño.setText("");
        cb_mazo.setSelectedIndex(0);
        cb_tipocarta.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_jb_agrmazoMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_agregarcartas.setVisible(true);
        jd_agregarcartas.pack();
        jd_agregarcartas.setModal(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(actual.getClan()==null){
        jd_crearclan.setVisible(true);
        jd_crearclan.pack();
        }
        else
            JOptionPane.showMessageDialog(jd_menu, "Para crear o unirse a un clan primero debes salir del actual");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        if(actual.getClan()==null){
            clanes.add(new Clan(tf_nombreclan.getText(), new Date(), actual,cb_rango.getSelectedItem().toString()));
            actual.setClan(clanes.get(clanes.size()-1));
            tf_nombreclan.setText("");
            cb_rango.setSelectedIndex(0);
        }
        else
            JOptionPane.showMessageDialog(jd_menu, "Para crear o unirse a un clan primero debes salir del actual");
    }//GEN-LAST:event_jb_crearMouseClicked

    private void jb_unirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_unirseMouseClicked

    }//GEN-LAST:event_jb_unirseMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(actual.getClan()==null){
            jd_unirclan.setVisible(true);
            jd_unirclan.pack();
            jd_unirclan.setModal(true);
            
            DefaultListModel modelo=(DefaultListModel)jl_clanes.getModel();
            for (Clan c : clanes) {
                modelo.addElement(c);
            }
            
            jl_clanes.setModel(modelo);
            
        }
        else
            JOptionPane.showMessageDialog(jd_menu, "Para crear o unirse a un clan primero debes salir del actual");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        actual.setClan(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_mazo;
    private javax.swing.JComboBox<String> cb_rango;
    private javax.swing.JComboBox<String> cb_tipocarta;
    private com.toedter.calendar.JDateChooser dc_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_agrmazo;
    private javax.swing.JButton jb_agrregistro;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_registro;
    private javax.swing.JButton jb_unirse;
    private javax.swing.JDialog jd_agregarcartas;
    private javax.swing.JDialog jd_crearclan;
    private javax.swing.JDialog jd_menu;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JDialog jd_unirclan;
    private javax.swing.JList<String> jl_clanes;
    private javax.swing.JList<String> jl_miembros;
    private javax.swing.JTree jt_mazos;
    private javax.swing.JPasswordField pf_agrpassword;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_agrapellido;
    private javax.swing.JTextField tf_agrnombre;
    private javax.swing.JTextField tf_agrusuario;
    private javax.swing.JTextField tf_nombrecarta;
    private javax.swing.JTextField tf_nombreclan;
    private javax.swing.JTextField tf_ptsdaño;
    private javax.swing.JTextField tf_ptsvida;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> usuarios=new ArrayList();
    Usuario actual;
    ArrayList<Clan> clanes=new ArrayList();
}
